on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - run: pip install --target "game/python-packages" -U ollama

      - name: Build VN project
        id: build_step
        uses: ProjectAliceDev/renpy-build-action@master
        with:
          sdk-version: '8.2.3'
          project-dir: '.'

      - name: Archive the build output
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ steps.build_step.outputs.dir }}